import { getServerSession } from "next-auth";
import "./globals.css";
import authOptions from "../utils/authOptions";
import SessionProvider from "../components/Providers/SessionProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          <main className="h-full flex bg-[#FAFAFB]">
            <div className="flex-1">{children}</div>
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
